{
 "title": "Checkout Use Case Dashboard",
 "description": "Dashboard for the checkout Use Case",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Checkout Traces",
   "type": "table",
   "description": "POST /checkout traces from webapp",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "operation": "POST /checkout", "service": "webapp" }
   ]
  },
  { "title": "Success/error rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "basket_checkout_success_total",
   "type": "timeseries",
   "description": "basket_checkout_success_total metric",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "basket_checkout_success_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "basket_checkout_error_total",
   "type": "timeseries",
   "description": "basket_checkout_error_total metric",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "basket_checkout_error_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "basket_checkout_success_total (overall per-second rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(basket_checkout_success_total{}[$__rate_interval]) * on (job, instance) group_left() topk by (job, instance) (1, target_info{}))",
     "legendFormat": "${metric} (overall per-second rate)"
    }
   ]
  },
  {
   "title": "basket_checkout_error_total (overall per-second rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(basket_checkout_error_total{}[$__rate_interval]) )",
     "legendFormat": "${metric} (overall per-second rate)"
    }
   ]
  },
  { "title": "Performance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "basket_checkout_latency_bucket",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(le) (rate(basket_checkout_latency_bucket{}[$__rate_interval]) )"
    }
   ]
  },
  {
   "title": "basket_checkout_latency_count (overall per-second rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(basket_checkout_latency_count{}[$__rate_interval]) )",
     "legendFormat": "${metric} (overall per-second rate)"
    }
   ]
  },
  {
   "title": "basket_checkout_latency_sum (average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(basket_checkout_latency_sum{}[$__rate_interval]) )/sum(rate(basket_checkout_latency_count{}[$__rate_interval]) )",
     "legendFormat": "basket_checkout_latency (average)"
    }
   ]
  },
  {
   "title": "Key Performance Indicators (KPIs)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }
  },
  {
   "title": "basket_checkout_items_bucket",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by(le) (rate(basket_checkout_items_bucket{}[$__rate_interval]) )"
    }
   ]
  },
  {
   "title": "basket_checkout_items_count (overall per-second rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(basket_checkout_items_count{}[$__rate_interval]) )",
     "legendFormat": "${metric} (overall per-second rate)"
    }
   ]
  },
  {
   "title": "basket_checkout_items_sum (average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(basket_checkout_items_sum{}[$__rate_interval]) )/sum(rate(basket_checkout_items_count{}[$__rate_interval]) )",
     "legendFormat": "basket_checkout_items (average)"
    }
   ]
  },
  {
   "title": "basket_checkout_value_USD_bucket",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by(le) (rate(basket_checkout_value_USD_bucket{}[$__rate_interval]) )"
    }
   ]
  },
  {
   "title": "basket_checkout_value_USD_count (overall per-second rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(basket_checkout_value_USD_count{}[$__rate_interval]) )",
     "legendFormat": "${metric} (overall per-second rate)"
    }
   ]
  },
  {
   "title": "basket_checkout_value_USD_sum (average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(basket_checkout_value_USD_sum{}[$__rate_interval]) )/sum(rate(basket_checkout_value_USD_count{}[$__rate_interval]) )",
     "legendFormat": "basket_checkout_value_USD (average)"
    }
   ]
  }
 ]
}